spring.datasource.url=jdbc:postgresql://localhost:5432/database_STOLB
spring.datasource.username=admin
spring.datasource.password=adm1n11
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update